// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/accountant/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accountant/guarantor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/guarantor">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/guarantor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accountant/loans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/loans">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/loans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accountant/savings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/savings">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/savings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accountant/shares/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/shares">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/shares/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/accountant/verify/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/accountant/verify">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/verify/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/accountants/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/accountants">> = Specific
  const handler = {} as typeof import("../../src/app/admin/accountants/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/analytics">> = Specific
  const handler = {} as typeof import("../../src/app/admin/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/admin/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/giveaway/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/giveaway">> = Specific
  const handler = {} as typeof import("../../src/app/admin/giveaway/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/guarantor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/guarantor">> = Specific
  const handler = {} as typeof import("../../src/app/admin/guarantor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/loans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/loans">> = Specific
  const handler = {} as typeof import("../../src/app/admin/loans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/savings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/savings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/savings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/shares/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/shares">> = Specific
  const handler = {} as typeof import("../../src/app/admin/shares/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/landing/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/landing">> = Specific
  const handler = {} as typeof import("../../src/app/landing/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/dashboard">> = Specific
  const handler = {} as typeof import("../../src/app/member/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/loan/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/loan">> = Specific
  const handler = {} as typeof import("../../src/app/member/loan/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/loan/request/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/loan/request">> = Specific
  const handler = {} as typeof import("../../src/app/member/loan/request/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/loans/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/loans">> = Specific
  const handler = {} as typeof import("../../src/app/member/loans/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/my-savings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/my-savings">> = Specific
  const handler = {} as typeof import("../../src/app/member/my-savings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/notifications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/notifications">> = Specific
  const handler = {} as typeof import("../../src/app/member/notifications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member">> = Specific
  const handler = {} as typeof import("../../src/app/member/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/payment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/payment">> = Specific
  const handler = {} as typeof import("../../src/app/member/payment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/savings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/savings">> = Specific
  const handler = {} as typeof import("../../src/app/member/savings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/shares/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/member/shares">> = Specific
  const handler = {} as typeof import("../../src/app/member/shares/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/member/shares/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/member/shares">> = Specific
  const handler = {} as typeof import("../../src/app/api/member/shares/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/accountant/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/accountant">> = Specific
  const handler = {} as typeof import("../../src/app/accountant/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/member/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/member">> = Specific
  const handler = {} as typeof import("../../src/app/member/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
